<?php

namespace Embajada\ValijaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OtrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtrosRepository extends EntityRepository
{
}
