<?php

namespace Embajada\ValijaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValijaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValijaRepository extends EntityRepository
{

    public function findporValija()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            select v , h
            from ValijaBundle:Valija v
            JOIN v.valija h
            ');
        	//JOIN v.id 0
       		//where  v.fechadefin between :fechai and :fechaf
            //$query->setParameter('fechai', new \DateTime('-10days'));
            //$query->setParameter('fechaf', new \DateTime('40days'));
            //CURRENT_DATE()
        	return $query->getResult();  
    }

}
