parameters:
#    documentos.example.class: Embajada\DocumentosBundle\Example

services:
#    documentos.example:
#        class: %documentos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
