<?php

namespace Embajada\EventosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends EntityRepository
{
}
