valija:
    pattern:  /
    defaults: { _controller: "ValijaBundle:Valija:index" }

valija_show:
    pattern:  /{id}/show
    defaults: { _controller: "ValijaBundle:Valija:show" }

valija_pdf:
    pattern:  /{id}/pdf
    defaults: { _controller: "ValijaBundle:Valija:pdf" }

valija_new:
    pattern:  /new
    defaults: { _controller: "ValijaBundle:Valija:new" }

valija_create:
    pattern:  /create
    defaults: { _controller: "ValijaBundle:Valija:create" }
    requirements: { _method: post }

valija_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ValijaBundle:Valija:edit" }

valija_update:
    pattern:  /{id}/update
    defaults: { _controller: "ValijaBundle:Valija:update" }
    requirements: { _method: post }

valija_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ValijaBundle:Valija:delete" }
    requirements: { _method: post }
