imports:
    #- { resource: @InventarioBundle/Resources/config/admin.xml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# app/config/config.yml
framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        []
    #java: /usr/bin/java
    filters:
        less:
          node: /usr/bin/node
          node_paths: [/opt/lessc/lib, /usr/lib/node_modules]
          apply_to: "\.less$"
        cssrewrite: ~
        #cssembed:
        #    jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
        #    apply_to: "\.css$|\.less$"
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        #    apply_to: "\.css$"
        #yui_js:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  namiayumis@gmail.com
    password:  Bachata.31

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Embajada\UserBundle\Entity\User
    registration:
        form:
            type: embajada_user_registration

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []
