parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     Siame
    database_user:     root
    database_password: Andr0id

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            es
    secret:            ThisTokenIsNotS0SecretChangeIt
