documentos:
    resource: "@DocumentosBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: InicioBundle:Default:index }

inicio:
    resource: "@InicioBundle/Resources/config/routing.yml"
    prefix:   /

valija:
    resource: "@ValijaBundle/Resources/config/routing.yml"
    prefix:   /

eventos:
    resource: "@EventosBundle/Resources/config/routing.yml"
    prefix:   /

orh:
    resource: "@OrhBundle/Resources/config/routing.yml"
    prefix:   /

inventarinicioio:
    resource: "@InventarioBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
notas:
    resource: "@NotasBundle/Resources/config/routing.yml"
    prefix:   /

NotasBundle_notascd:
    resource: "@NotasBundle/Resources/config/routing/notascd.yml"
    prefix:   /notascd

NotasBundle_notas:
    resource: "@NotasBundle/Resources/config/routing/notas.yml"
    prefix:   /notas

OrhBundle_personal:
    resource: "@OrhBundle/Resources/config/routing/personal.yml"
    prefix:   /personal

OrhBundle_vacaciones:
    resource: "@OrhBundle/Resources/config/routing/vacaciones.yml"
    prefix:   /vacaciones

EventosBundle_categoria:
    resource: "@EventosBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

EventosBundle_contacto:
    resource: "@EventosBundle/Resources/config/routing/contacto.yml"
    prefix:   /contactos

EventosBundle_evento:
    resource: "@EventosBundle/Resources/config/routing/evento.yml"
    prefix:   /evento

ValijaBundle_hremision:
    resource: "@ValijaBundle/Resources/config/routing/hremision.yml"
    prefix:   /hremision

ValijaBundle_Oficios:
    resource: "@ValijaBundle/Resources/config/routing/oficios.yml"
    prefix:   /Oficios

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hremision_aprobar:
    pattern:  /{id}/aprobar
    defaults: { _controller: "ValijaBundle:Hremision:aprobar" }
    options:
        expose: true