# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            security:     true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_USER }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/personal/, role: ROLE_ADMIN }
        - { path: ^/notas/, role: ROLE_USER }
        - { path: ^/notascd/, role: ROLE_USER }
        - { path: ^/vacaciones/, role: ROLE_USER }
        - { path: ^/hremision/, role: ROLE_USER }
        - { path: ^/Memoi/, role: ROLE_USER }
        - { path: ^/Libros/, role: ROLE_USER }
        - { path: ^/Oficios/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
