services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

    intl.twig.extension:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension' }]

    twig.extension.notas:
        class: Embajada\NotasBundle\Twig\Extension\NotasExtension
        tags:
            - { name: twig.extension }

    acme_user.registration.form.type:
        class: Embajada\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: embajada_user_registration }

    sonata.embajada.admin.inventario:
        class: Embajada\InventarioBundle\Admin\InventarioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Inventario', label: Bienes }
        arguments:
            - null
            - Embajada\InventarioBundle\Entity\Bien
            - InventarioBundle:Admin