services:
    embajada_user.registration.form.type:
        class: Embajada\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: embajada_user_registration }