parameters:
#    inventario.example.class: Embajada\InventarioBundle\Example

services:
#    inventario.example:
#        class: %inventario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
