<?php

namespace Embajada\OrhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompensatoriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompensatoriosRepository extends EntityRepository
{
}
