evento:
    pattern:  /
    defaults: { _controller: "EventosBundle:Evento:index" }

evento_show:
    pattern:  /{id}/show
    defaults: { _controller: "EventosBundle:Evento:show" }

evento_new:
    pattern:  /new
    defaults: { _controller: "EventosBundle:Evento:new" }

evento_create:
    pattern:  /create
    defaults: { _controller: "EventosBundle:Evento:create" }
    requirements: { _method: post }

evento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EventosBundle:Evento:edit" }

evento_update:
    pattern:  /{id}/update
    defaults: { _controller: "EventosBundle:Evento:update" }
    requirements: { _method: post }

evento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EventosBundle:Evento:delete" }
    requirements: { _method: post }
